### ISSUE TITLE
Access request

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/com.adobe.acs.bundles.netty#1]
May I please have access to push package icon changes to this project (or branch for PR if you'd rather)

**Comment by justinedelson** [comment]
done

**Comment by davidjgonzalez** [comment]
thanks! i added the thumbnail.png to the root of the project and didnt bother with the "normal" vault folder structure or resources. Let me know if youd rather them be put someplace else.
